[package]
name = "optiga-m"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2.7"
num-derive = "0.3.3"
num_enum = { version = "0.5.6", default-features = false, features = ["complex-expressions"] }
optiga-m-sys = { path = "../optiga-m-sys" }
